// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoMblxntzCV5eYqS2OpYPnOPQXns7CVV0',
    appId: '1:186928034819:web:047764391d9c6dcfee8a36',
    messagingSenderId: '186928034819',
    projectId: 'mechanic-pro-7',
    authDomain: 'mechanic-pro-7.firebaseapp.com',
    storageBucket: 'mechanic-pro-7.firebasestorage.app',
    measurementId: 'G-T5RZD6CMBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHS5P3SwUn6ihbeM7-ioeUalUxwaFt-Fw',
    appId: '1:186928034819:android:08475293890682adee8a36',
    messagingSenderId: '186928034819',
    projectId: 'mechanic-pro-7',
    storageBucket: 'mechanic-pro-7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEl1r8Vd4oLn-aMbR3saR2eckcTzTewsQ',
    appId: '1:186928034819:ios:de0dff91090bcd54ee8a36',
    messagingSenderId: '186928034819',
    projectId: 'mechanic-pro-7',
    storageBucket: 'mechanic-pro-7.firebasestorage.app',
    iosBundleId: 'com.ElJabir.MechanicProApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEl1r8Vd4oLn-aMbR3saR2eckcTzTewsQ',
    appId: '1:186928034819:ios:de0dff91090bcd54ee8a36',
    messagingSenderId: '186928034819',
    projectId: 'mechanic-pro-7',
    storageBucket: 'mechanic-pro-7.firebasestorage.app',
    iosBundleId: 'com.ElJabir.MechanicProApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoMblxntzCV5eYqS2OpYPnOPQXns7CVV0',
    appId: '1:186928034819:web:7d30e691fa624923ee8a36',
    messagingSenderId: '186928034819',
    projectId: 'mechanic-pro-7',
    authDomain: 'mechanic-pro-7.firebaseapp.com',
    storageBucket: 'mechanic-pro-7.firebasestorage.app',
    measurementId: 'G-JE7TYTR03X',
  );
}
